### PR TITLE
Make methods async

### LINKED ISSUE #190: Make Impl methods `async`?
Would be nice if all the methods were declared as `async` / returning `Promise<>` so I can `await` in them if needed. As far as I can see they are currently called in async functions in `wrapper.ts.hbs`

What do you think? It will be a breaking change but fairly straight-forward to do.

### PR DESCRIPTION
**Pull request by hpx7**
Fixes https://github.com/hathora/hathora/issues/190

### CODE REVIEW

**Comment by hpx7** [comment]
Docs need to updated before this is merged

**Comment by kasbah** [comment]
They way this is now, you can dispatch multiple method calls asynchronously indirectly [here](
https://github.com/hathora/hathora/blob/5ab36784a1275d9653f3c3813a250c90a93517fd/templates/base/server/.hathora/protocol.ts.hbs#L61). If I understood it correctly you would need a blocking read of the socket that only fires one async callback at a time and awaits it. 

~~Thinking about it further. You may have had this problem on the `develop` branch already. Is it not possible dispatch multiple calls of `handleUpdate` which is async, and it in turn calls the (currently sync) `Impl` methods?~~ Nevermind, I sometimes forget async is still only one thread.

**Comment by hpx7** [comment]
I don't think we need to await at the socket level since we do the await here: https://github.com/hathora/hathora/blob/31d2655b474453b4310d063b98de50f6f6fc0463/templates/base/server/.hathora/store.ts.hbs#L100

**Comment by kasbah** [comment]
You can have multiple `handleUpdate` calls running at the same time though.

**Comment by hpx7** [comment]
> You can have multiple handleUpdate calls running at the same time though.

I think that's fine? They will just queue at the `impl.getResult()` call. As long as the impl methods themselves run serially I think it's fine.

**Comment by kasbah** [comment]
If you `await` inside a method the event loop goes to the next call. So something like:

1. Data comes in on the socket
1. `handleUpdate` gets called
1. an async `method1` gets called
1. ` method1` `await`s something , it has not finished
1. Data comes in on the socket
1. `handleUpdate` gets called
1. an async `method2` gets called
1. `method2` `await`s something
1. the event loop resumes the rest of `method1` after the `await`

So they are interleaved.

**Comment by hpx7** [comment]
Ah you are right.

I may need to use https://github.com/DirtyHairy/async-mutex for this

**Pull request closed without merging**
